<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css' />
    <link href="/css/bootstrap.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="/css/font-awesome.css" />
    
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="/js/bootstrap.js"></script>
<script type="text/javascript" src="/js/jquery.orbit-1.2.3.js"></script>	
<link rel="stylesheet" href="/css/orbit-1.2.3.css" />    
    <script type="text/javascript" src="http://cdn.connect.mail.ru/js/loader.js"></script>
    
    <script src="/js/j.js"></script>
    <link href="http://www.odnoklassniki.ru/oauth/resources.do?type=css" rel="stylesheet" />
    <script src="http://www.odnoklassniki.ru/oauth/resources.do?type=js" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" href="/css/s.css" />
    <title>DonorSearch</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
</head>
<body class="chrome">
    <?php require 'forms/main.phtml' ; ?>     
</body></html>