<div class="span9" style="outline:0px dotted gray;">
      
      <div class="row-fluid">
        <h2 style="margin:0px;margin-top:-10px;" id="how">Как это работает</h2>
      </div>
      <div id="slider">
       <style>
		.orbit-bullets li.has-thumb {
    width: 128px;
    height: 61px; }
		</style>
		
<div class="container11" style="height:350px;padding-top:15px;">
		<div class="orbit-wrapper"><div id="featured11" style="overflow: hidden; width: 400px; height: 300px;" class="orbit"> 
			<img src="img/slider/1.png" data-caption="#text1" style="z-index: 3; display: block;">
			<img src="img/slider/2.png" data-caption="#text2" style="display: block;">
			<img src="img/slider/3.png" data-caption="#text3" style="display: block;">
			<img src="img/slider/4.png" data-caption="#text4" style="display: block;">
			<img src="img/slider/5.png" data-caption="#text5" style="display: block;">
		</div><div class="orbit-caption" id="#text1" style="display: block;">
		<h2>Шаг 1 из 5</h2>
		«Ищущий» заходит на сайт <span class="bold">DonorSearch</span>, где быстро и&nbsp;легко подбирает нужных доноров. Он в пару кликов отправляет им информацию о месте сдачи крови и спрашивает разрешения с ними связаться.<br><br>
		В результатах поиска выпадают только актуальные на данный момент профили доноров.  
		</div><div class="slider-nav"><span class="rightorbit">Right</span><span class="leftorbit">Left</span></div><ul class="orbit-bullets"><li class="active">1</li><li>2</li><li>3</li><li>4</li><li>5</li></ul></div>
		<!-- Captions for Orbit -->
		<span class="orbit-caption" id="text1">
		<h2>Шаг 1 из 5</h2>
		«Ищущий» заходит на сайт <span class="bold">DonorSearch</span>, где быстро и&nbsp;легко подбирает нужных доноров. Он в пару кликов отправляет им информацию о месте сдачи крови и спрашивает разрешения с ними связаться.<br><br>
		В результатах поиска выпадают только актуальные на данный момент профили доноров.  
		</span>
		<span class="orbit-caption" id="text2">
		<h2>Шаг 2 из 5</h2>
		Доноры, отметившие, что они могут сдавать кровь сейчас, получают мгновенное <span class="bold">sms-сообщение</span> с призывом помочь и&nbsp;информацией о том, где они могут это сделать.<br> 
		<br>Доноров зовут на станцию переливания, находящуюся в их или близлежащем районе.
		</span>
		<span class="orbit-caption" id="text3">
		<h2>Шаг 3 из 5</h2>
		Доноры узнают подробности, <span class="bold">подтверждают</span> свое согласие помочь и&nbsp;отправляют свои контактные данные «Ищущему». Происходит это в&nbsp;один клик.<br><br>
		Без личного согласия донора его контактные данные не доступны. 
		</span>
		<span class="orbit-caption" id="text4">
		<h2>Шаг 4 из 5</h2>
		«Ищущий» звонит донорам, чтобы подробно договориться о дне и времени встречи на станции переливания.
		</span>
		<span class="orbit-caption" id="text5">
		<h2>Шаг 5 из 5</h2>
		Доноры сдают кровь. Пополняют банк крови на станции.<br><br>
		«Ищущий» получает справки о сдачах крови донорами. Его нуждающемуся родственнику(другу) осуществляют переливание.
		</span>
		
	</div>      </div>
    <script>
        $(function(){
            $('#featured11').orbit({bullets:true});
        });
    </script>
      <div class="row-fluid">
        <h2 style="margin-left:0px;margin-top:-10px;" id="mission">Наша миссия</h2>
      </div>
<p>В настоящий момент остается актуальной проблема острой нехватки донорской крови. Для переливания донорской крови местные больницы требуют эквивалент крови, которая необходима для лечения реципиента.</p> 

<p>Проект направлен на поиск тех людей, которые готовы помочь, приехать и сдать кровь, но не готовы сдавать кровь систематически, постоянно ежемесячно по тем или иным причинам - молодому человеку не хочется, это и низкая мотивация, низкое информированность о важности донорства, нехватка времени и т.д.</p>

<p>Также "Поиск Доноров" позволяет заносить себя в базу даже, если пользователь не знает свой резус и группу – так называемый донор на замену. Это позволяет впервые стать донором, когда его попросят (как мотивация для первой кроводачи) и, возможно, в последствии стать кадровым донором.</p>

<p>То есть, мы конечно же за кадровое донорство, но проблемой популяризации занимаются многие организации, мы же выбрали вот такой путь, ведь впервые адресно сдав кровь, кто-то может поймет, что это не сложно и главное очень нужно и, в последствии, станет кадровым донором, а те, кто уже сдавал, но забылся или сдает не систематически, участие в проекте позволит поставить такой "будильник" для очередной кроводачи.</p>
      
      <div class="row-fluid">
        <h2 style="margin-left:0px;" id="crew">Команда</h2>
      </div>
      <style>
        .row-fluid .span4
        {
            margin-left:0;
            margin-top:10px;
            margin-right:5px;
        }
      </style>
      <div class="row-fluid">
      
        <div class="span4 thumbnail" style="">
          <a href="http://vk.com/shekurov" target="_blank"><img src="/img/ruslan.jpg" class="img-rounded" style="margin-left: 25px;width:157px;height:157px;margin-top:15px;" /></a> 
          <center style="font-size:1.2em;padding:20px;padding-bottom:0px;">Руслан Шекуров</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>Руководитель и автор</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="mailto:russel86@rambler.ru">russel86@rambler.ru</a></center>
        </div> 
           
        <div class="span4 thumbnail">
          <img src="img/vitalka.jpg" class="img-rounded" style="width:157px;height:157px;margin-top:15px;">
          <center style="font-size:1.2em;padding:20px;padding-bottom:0px;">Виталий Архипов</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>Главный разработчик</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="mailto:arvitaly@list.ru">arvitaly@list.ru</a></center>
        </div>      
        <div class="span4 thumbnail">
          <img src="img/avatar.png" class="img-rounded" style="width:157px;height:157px;margin-top:15px;">
          <center style="font-size:1.2em;padding:20px;padding-bottom:0px;">Роман Карпов</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>CEO</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">&nbsp;</a></center>
        </div>
        <div class="span4 thumbnail">
          <img src="img/kran.png" class="img-rounded" style="width:157px;height:157px;margin-top:15px;">
          <center style="font-size:1.2em;padding:20px;padding-bottom:0px;">Илья Кранов</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>CТО</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">&nbsp;</a></center>
        </div>
        <div class="span4 thumbnail" style="">
          <img src="/img/almaz.jpg" class="img-rounded" style="width:157px;height:157px;margin-top:15px;">
          <center style="font-size:1.2em;padding:20px;padding-bottom:0px;">Алмаз Загидуллин</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>Ответственный по финансам</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">https://vk.com/almaz_zagidullin</a></center>
        </div>         
        <div class="span4 thumbnail">
          <img src="img/yu.png" class="img-rounded" style="width:157px;height:157px;margin-top:15px;">
          <center style="font-size:1.2em;padding:20px;padding-bottom:0px;">Юлиана Хризман</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>HR</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">&nbsp;</a></center>
        </div>
      </div>
      <style>
        .row-fluid .span3
        {
            margin-left:0;
            margin-top:10px;
            margin-right:12px;
            width: 22%;
        }
      </style>      
      <div class="row-fluid">
        <h2 style="margin-left:0px;margin-top:20px;margin-bottom:0px;">Спасибо</h2>
      </div>
      <div class="row-fluid" style="margin-top:15px;">
        <div class="span3 thumbnail">
          <img src="img/su.png" class="img-rounded" style="width:120px;height:120px;margin-top:10px;">
          <center style="font-size:1.1em;padding:20px;padding-bottom:10px;">Сюзанна Белкина</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>Иллюстратор</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">suzan@li.ru</a></center>
        </div>
        <div class="span3 thumbnail">
          <img src="img/photos/bolgov157.jpg" class="img-rounded" style="width:120px;height:120px;margin-top:10px;">
          <center style="font-size:1.1em;padding:20px;padding-bottom:10px;">&nbsp;&nbsp;Антон &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Болгов&nbsp; &nbsp;</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>Неуемный донор</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">&nbsp;&nbsp;&nbsp;</a></center>
        </div>
        <div class="span3 thumbnail">
          <img src="img/photos/permyakova157.jpg" class="img-rounded" style="width:120px;height:120px;margin-top:10px;">
          <center style="font-size:1.1em;padding:20px;padding-bottom:10px;">Светлана Пермякова</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>Победитель тест-камп</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">&nbsp;&nbsp;&nbsp;</a></center>
        </div>
        <div class="span3 thumbnail">
          <img src="img/photos/vagin157.jpg" class="img-rounded" style="width:120px;height:120px;margin-top:10px;">
          <center style="font-size:1.1em;padding:20px;padding-bottom:10px;">&nbsp;&nbsp;Андрей &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Вагин&nbsp; &nbsp;</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>Хранитель</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">&nbsp;&nbsp;&nbsp;</a></center>
        </div>
        <div class="span3 thumbnail">
          <img src="img/photos/bruzgin157.jpg" class="img-rounded" style="width:120px;height:120px;margin-top:10px;">
          <center style="font-size:1.1em;padding:20px;padding-bottom:10px;">&nbsp;&nbsp;Виталий &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Брузгин&nbsp; &nbsp;</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>&nbsp;&nbsp;&nbsp;</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">&nbsp;&nbsp;&nbsp;</a></center>
        </div>
        <div class="span3 thumbnail">
          <img src="img/photos/madjidov157.jpg" class="img-rounded" style="width:120px;height:120px;margin-top:10px;">
          <center style="font-size:1.1em;padding:20px;padding-bottom:10px;">&nbsp;&nbsp;Тимур &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Маджидов</center>
          <center style="font-size:0.8em;color:gray;padding-bottom:0px;"><i>&nbsp;&nbsp;&nbsp;</i></center>
          <center style="font-size:0.8em;color:gray;padding-bottom:15px;"><a href="#">&nbsp;&nbsp;&nbsp;</a></center>
        </div>
 
      </div>
      
      <div class="row-fluid" style="margin-top:15px;" id="sponsors">
         <h2 style="margin-left:0px;margin-bottom:0px;">Партнеры и спонсоры</h2>
      </div>
      
      <hr>
      <div class="row-fluid" style="margin-top:25px;">
        <div class="span5 thu4mbnail">
          <a href="http://tatmol.tatarstan.ru/" target="_blank"><img src="/img/FZd8fLzmaDI.jpg" style="max-height:90px;max-width:200px;align:right;" /></a>
        </div>
        <div class="span7 thum5bnail">
          Союз молодежи Республики Татарстан <br>
          <i>Информационный партнер</i>
        </div>
      </div>       
      
      <hr>
      <div class="row-fluid" style="margin-top:25px;">
        <div class="span5 thu4mbnail">
          <a href="http://te-st.ru/" target="_blank"><img src="http://te-st.ru/wp-content/uploads/300-100.png" style="max-height:90px;max-width:200px;align:right;" /></a>
        </div>
        <div class="span7 thum5bnail">
          Теплица социальных технологий <br>
          <i>Информационный партнер</i>
        </div>
      </div>      
      <hr>
      <div class="row-fluid" style="margin-top:25px;">
        <div class="span5 thu4mbnail">
          <a href="http://spbredcross.org" target="_blank"><img src="img/redcross_l.png" style="max-height:90px;max-width:200px;align:right;"></a>
        </div>
        <div class="span7 thum5bnail">
          Санкт-Петербургское отделение Российского&nbsp;Красного&nbsp;Креста <br>
          <i>Информационный партнер</i>
        </div>
      </div>
      <hr>
      <div class="row-fluid" style="margin-top:30px;">
        <div class="span5 thum5bnail">
          <a href="http://volonte.ru" target="_blank"><img src="img/club25.jpg" style="max-height:90px;max-width:200px;right:0px;"></a>
        </div>
        <div class="span7 thum5bnail">
          Международный клуб молодых доноров «Клуб25» <br>
          <i>Информационный партнер</i>
        </div>
      </div>
      <hr>
      <div class="row-fluid" style="margin-top:30px;">
        <div class="span5 thum5bnail">
          <a href="http://sms.ru" target="_blank"><img src="img/sms.png" style="max-height:90px;max-width:200px;right:0px;"></a>
        </div>
        <div class="span7 thum5bnail">
          Центр смс-рассылок<br>
          <i>Спонсор</i>
        </div>
      </div>
      <hr>
      <div class="row-fluid" style="margin-top:30px;">
        <div class="span5 thum5bnail">
          <a href="http://sumit.ru" target="_blank"><img src="img/sumit.png" style="max-height:90px;max-width:200px;right:0px;"></a>
        </div>
        <div class="span7 thum5bnail">
          Стартап школа SUMIT<br>
        </div>
      </div>
      <hr>
      <div class="row-fluid" style="margin-top:30px;">
        <div class="span5 thum5bnail">
          <a href="http://it-start.pro" target="_blank"><img src="img/itstart.png" style="max-height:90px;max-width:200px;right:0px;"></a>
        </div>
        <div class="span7 thum5bnail">
          IT-школа<br>
        </div>
      </div>
      
      <br>
    </div>