<div class="span9" style="outline:0px dotted gray;">
      
      <div class="row-fluid">
        <h2 style="margin:0px;margin-top:-10px;" id="how">Помочь проекту</h2>
      </div>
<p>За почти 2 года нашей деятельности, в приложении уже более 5000 пользователей и больше <a href="http://vk.com/topic-21179173_24022855">120 отзывов</a> о том, как помог ПОИСК ДОНОРОВ найти отзывчивых людей - и мы знаем, что положительных поисков на самом деле еще больше!</p> 

<p>Эти 2 года были тестом нашей идеи на ее продуктивность и необходимость - и она полностью оправдала наши ожидания. И вот теперь, мы хотим сделать идею Поиска самым большим и удобным сервисом - и, к сожалению, это очень сложно сделать без финансовых вложений.</p> 

<p>Нам нужны деньги на разработку и поддержку сайта и, конечно же, на рекламу для привлечения новых доноров в базу ПОИСКА. </p>

<p>Если Вы пользуетесь нашим сервисом, но у Вас нет достаточно денег, то ни в коем случае не тратьте их на поддержку в знак благодарности. Мы просим деньги у тех, кто действительно может отдать незначительную для него часть денег на благое дело, которое доказало свое право на жизнь!</p>      
</div>
<center>
<iframe style="margin-top: 10px;" frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/donate.xml?uid=410011495515799&amp;default-sum=100&amp;targets=%d0%a0%d0%b0%d0%b7%d0%b2%d0%b8%d1%82%d0%b8%d0%b5+%d0%bf%d1%80%d0%be%d0%b5%d0%ba%d1%82%d0%b0&amp;target-visibility=on&amp;project-name=%d0%9f%d0%be%d0%b8%d1%81%d0%ba+%d0%b4%d0%be%d0%bd%d0%be%d1%80%d0%be%d0%b2&amp;project-site=http%3a%2f%2fvk.com%2fdonorsearch&amp;button-text=01&amp;comment=on&amp;hint=%d0%9f%d0%be%d0%b6%d0%b0%d0%bb%d1%83%d0%b9%d1%81%d1%82%d0%b0%2c+%d1%80%d0%b0%d1%81%d1%81%d0%ba%d0%b0%d0%b6%d0%b8%d1%82%d0%b5+%d0%be+%d1%82%d0%be%d0%bc%2c+%d0%bf%d0%be%d1%87%d0%b5%d0%bc%d1%83+%d0%b4%d0%bb%d1%8f+%d0%92%d0%b0%d1%81+%d0%b2%d0%b0%d0%b6%d0%bd%d0%be+%d1%80%d0%b0%d0%b7%d0%b2%d0%b8%d1%82%d0%b8%d0%b5+%d0%bf%d1%80%d0%be%d0%b5%d0%ba%d1%82%d0%b0&amp;fio=on&amp;mail=on&amp;phone=on" width="450" height="205"></iframe>
</center> 