       <div class="row-fluid">
            <div class="span6" style="">
                <h1 style="text-align:center;">О проекте</h1>
                    <p style="font-size:0.9em;padding-top:10px;">Проект дает возможность донорам и людям, нуждающимся в них, быстрее и проще находить друг друга.
К сожалению, далеко не все объявления в социальных сетях настоящие, а сотни людей ежедневно действительно нуждаются в срочном переливании, в то время как есть много людей, действительно готовых помочь!</p>
 <p style="font-size:0.9em;padding-top:10px;">Используйте этот добрый сервис только для поиска доноров крови или компонентов крови. А также заносите себя в базу данных, только если Вы действительно готовы и можете сдать кровь, когда Вас попросят, при условии, что Вам в эти сроки будет удобно.</p>
                    </p>
            </div>
 
<div class="span6">   
        <div class="row-fluid">
          <div class="span12" style="height:100px;"><h4 style="margin-top:70px;">Нас поддерживают</h4></div>
        </div>  
        <div class="row-fluid" style="margin-top:10px;">
          <div class="span9" style="height:100px;padding:10px;"><a href="http://te-st.ru/" target="_blank"><img src="http://te-st.ru/wp-content/uploads/300-100.png" style="height:80px;"></a></div>
          <div class="span3" style="height:100px;padding:10px;"><a href="http://volonte.ru/" target="_blank"><img src="img/club25.jpg" style="height:80px;"></a></div>
        </div>  

        
        
      </div>              
        </div>
    <hr />
    <div class="row-fluid" >
        
        
          <div class="span5 offset1 thumbnail" style="height:500px;">
            <h2 align="center">Поиск донора</h2>
            <a href="/search" class="shover"></a>
            <p style="padding:10px 30px 10px 30px;font-size:0.9em;">Чтобы найти донора - выберите страну и город, а также группу и резус-фактор необходимой донорской крови. В случае, когда кровь не важна выберите пункт - группа крови любая.</p><p>&nbsp;</p><p>&nbsp;</p>
             <a href="/search">
             <div class="span4 offset4 thumbnail" style="margin-bottom:15px;"><button type="button" class="btn btn-block btn-danger" style="margin:auto;">Поиск</button></div></a>
             
          </div>
          
          <div class="span5 thumbnail" style="height:500px;">
            <h2 style="text-align:center;">Регистрация</h2>
            <a href="/reg" class="phover"></a>
            <p style="padding:10px 30px 10px 30px;font-size:0.9em;">Регистрируясь, Вы подверждаете свое согласие на обработку указанных Вами данных. Укажите страну и город, где Вы проживаете, а также группу крови и резус-фактор. Если группа крови не известна - выберите соответсвующий пункт. Подробную информацию о донорстве крови можно прочесть <a href="/info">здесь</a>.</p>
            <a href="/reg">
            <div class="span4 offset4 thumbnail" style="margin-bottom:15px;"><button type="button" class="btn btn-block btn-danger" style="margin:auto;">Регистрация</button></div></a>
          </div>      
    </div>
    <center>
<div id="vk_groups" style="margin-top:60px;"></div>
</center>    
<script type="text/javascript">
Vkontakte.init(function(){
    VK.Widgets.Group("vk_groups", {mode: 0, width: "750", height: "400"}, 21179173);    
});
</script>     