<div class="row-fluid" style="height:60px;">
                            <a href="javascript:void(0);" style="text-decoration:none;">
                                <p style="margin-top:5px;line-height: 100%;text-align:center;">
                                    <br /><i class="icon-user" style="margin:0px;margin-top:0px;"></i>
                                       <br /><a role="button" class="btn" href="#modalauth" data-toggle="modal">Авторизация</a>
                                </p>
                            </a>
                        </div>

<div id="modalauth" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Авторизация</h3>
  </div>
  <div class="modal-body">
    <p>
    <?php
        foreach( $socnetworks as $name => $s )
        {
            echo '<a onclick="" href="" sn="' . $name . '" rel="nofollow" class="ico"><img src="img/ico_' . $name . '.png" width="40" height="40" title="Авторизация через ' . $name::$TITLE . '" /></a>&nbsp;&nbsp;&nbsp;';
        }
    ?>
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Закрыть</button>
  </div>
</div>
<script>
    $('#modalauth a[sn]').click(function(){
        
        socnetwork.auth( $(this).attr('sn') );
        return false;
    });
</script>