<?php
    $user = User::get();
?>
<div class="row-fluid" style="height:60px;">
  <a href="/donor" style="text-decoration:none;">
    <p style="margin-top:5px;line-height: 100%;" align="center"><i class="icon-user" style="margin:0px;margin-top:0px;"></i><br><?php echo $user->first_name;  ?><br><?php echo $user->last_name;  ?></p>
    
  </a>
</div>
<div class="row-fluid" style="height:30px;">
  <hr style="margin:0px;" />
  <button class="btn btn-link" style="margin-top:0px;margin-left:20px;" onclick="actions.triggerOnServer('exit');">Выход<i class="icon-signout" style="padding-left:5px;padding-top:1px;"></i></button>
</div>